name: Workflow for automation

# trigger
on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build Laravel App
    runs_on: ubuntu_latest
    steps:
      - name: Hello
        run: |
            echo "Hello"
      
